test_interview:
    resource: "@TestInterviewBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hello:
  path: /hello
  defaults: {_controller: AppBundle:Default:hello}