<?php
// Demande 7, créé par generate
namespace Test\InterviewBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BiosRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BiosRepository extends DocumentRepository
{
    // Demande 8.1
    public function findByFirstName($firstName)
    {
        $result = $this->createQueryBuilder()
            ->find()
            ->field('name.first')->equals($firstName)
            ->getQuery()
            ->execute()
            ->toArray();
        // toujours tester qu'il existe un résultat sinon on retourne false pour éviter un 404
        if (empty($result))
            return false;
        // on assume le fait que plusieurs personnes peuvent avoir le même prénom
        // donc on retourne toujours un tableau d'objet BiosDocument
        foreach($result as $bios){
            $data[] = $bios;
        }
        return $data;
    }

    // Demande 8.2
    public function findByContribution($contributionName)
    {
        $result = $this->createQueryBuilder()
            ->find()
            ->field('contribs')->equals($contributionName)
            ->getQuery()
            ->execute()
            ->toArray();
        if (empty($result))
            return false;
        foreach($result as $bios){
            $data[] = $bios;
        }
        return $data;
    }

    // Demande 8.3
    public function findByDeadBefore($year)
    {
        // On assume le fait que le décès doit être avant le 01/01/$year 00:00:00
        $date_search =  new \MongoDate(strtotime("$year-01-01 00:00:00"));
        $result = $this->createQueryBuilder()
            ->find()
            ->field('death')->lte($date_search)
            ->getQuery()
            ->execute()
            ->toArray();
        return $result;
    }

}
