<?php

namespace Test\InterviewBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BiosRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BiosRepository extends DocumentRepository
{
    // Test perso
    public function findAllOrderedById()
    {
        return $this->createQueryBuilder()
            ->sort('id', 'DESC')
            ->getQuery()
            ->execute()
            ->toArray();
    }

    // on assume le fait que plusieurs personnes peuvent avoir le même prénom
    // donc on retourne toujours un tableau d'objet BiosDocument
    public function findByFirstName($firstName)
    {
        $result = $this->createQueryBuilder()
            ->find()
            ->field('name.first')->equals($firstName)
            ->getQuery()
            ->execute()
            ->toArray();
        if (empty($result))
            return false;
        foreach($result as $bios){
            $data[] = $bios;
        }
        return $data;
    }

    public function findByContribution($contributionName)
    {
        $result = $this->createQueryBuilder()
            ->find()
            ->field('contribs')->equals($contributionName)
            ->getQuery()
            ->execute()
            ->toArray();
        if (empty($result))
            return false;
        foreach($result as $bios){
            $data[] = $bios;
        }
        return $data;
    }

    public function findByDeadBefore($year)
    {
        $date_search =  new \MongoDate(strtotime("$year-01-01 00:00:00"));
        $result = $this->createQueryBuilder()
            ->find()
            ->field('death')->lte($date_search)
            ->getQuery()
            ->execute()
            ->toArray();

        return $result;
    }

}
